name: Bug Report
description: Report a bug in Attestia
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen.
    validations:
      required: true
  - type: input
    id: package
    attributes:
      label: Package
      description: Which package is affected?
      placeholder: e.g. @attestia/vault, @attestia/witness
  - type: input
    id: version
    attributes:
      label: Node.js version
      placeholder: e.g. 22.x
